server:
  port: 8089

spring:
   cloud:
     config:
       server:
         git:
           #uri: https://github.com/diegolucasilva/aws-configs-store
           uri: https://git-codecommit.sa-east-1.amazonaws.com/v1/repos/aws-configs-store